### ISSUE TITLE
Pinned Apps Crash Launcher When Moved

### ISSUE THREAD

**Issue by oneofmanyacdcfans** [F4uzan/HgLauncher#20]
If there are more than 5 apps pinned, and you try to reorder any of them after the fifth one, the launcher crashes out with the error message "Unfortunately, HGlauncher has stopped" and I'm presented with the option to choose launcher before continuing. The workaround is that you have to start by tap-and-hold moving the fifth pinned app and moving it behind the others, and repeating that process until the icons are arranged in the order desired. 

HTC Desire 510 on KitKat 4.4.2

**Comment by F4uzan** [comment]
This doesn't seem to occur for me. I'll dig up some old devices to see if it's an API-specific issue. In the meantime, are you in any way able to capture logs before the crash?

**Comment by oneofmanyacdcfans** [comment]
I'm not sure how to do that. If you can instruct me I will try.

**Comment by F4uzan** [comment]
The referenced commit should fix this issue once and for all. It doesn't seem to occur in later version (9.0), or it never once occurred — but it does happen in practically anything else below 9.0.

That being said, this is an issue that's mostly caused by my oversight (the fix was already available several lines above it). Let's hope these never happen again.
