### ISSUE TITLE
Use Startpage.com instead of Google?

### ISSUE THREAD

**Issue by comradekingu** [F4uzan/HgLauncher#44]
Google is not good for privacy, Startpage at-least purports to do the same, with added privacy.

**Comment by F4uzan** [comment]
While I agree with you there (I use searx myself), a good chunk of users still use Google as their default search engine. Removing it now would be a rather odd decision, since they themselves can remove it.

Though with that said, we can introduce Startpage to the list of default search engines. There shouldn't be much difficulty in that.

**Comment by macdonaldster** [comment]
To implement this correctly, would you expect a POST request to Starpage.com or would a GET request be OK?

Example: https://www.startpage.com/do/search?query=how%20does%20it%20work

**Comment by F4uzan** [comment]
GET should work fine, I suppose. We only need to add its entry in PreferenceHelper and arrays.xml. The existing providers should give a good enough clue as to how it is implemented.

I'd refer to https://github.com/F4uzan/HgLauncher/commit/77113d0c7805f02c2dd54d6600059d2a5eed2030 in case there's a plan to implement this.

**Comment by F4uzan** [comment]
The commits linked should have Startpage implemented all correctly. I'll be closing this unless there's further question regarding the manner.
