### ISSUE TITLE
Search does not apply after applications are loaded

### ISSUE THREAD

**Issue by fynngodau** [F4uzan/HgLauncher#48]
When a string is entered into the search bar while the application list is still loading, this search does not automatically get applied once the list is done loading (you have to type or remove a character for the search to trigger).

**Comment by F4uzan** [comment]
If I'm not mistaken, this was put because I didn't want the filter to accidentally filter in an incomplete list — but I do see the problem here, especially with the 'keep search text' option, wherein the search text would simply refuse to be applied until it is altered.

I have a concrete idea of where this might occur in the code. We'll see if I can get this fixed tomorrow.

**Comment by macdonaldster** [comment]
Sounds good. I am sorry I haven't done much on this. I have been travelling
(family + work).

**Comment by F4uzan** [comment]
It's perfectly okay! I've been trying to work around this issue in particular because apparently what I thought was correct: removing the check causes the search to filter an incomplete list of apps.

We might need to do some chunk of rework on that, but I'm currently getting Work/alternate profile to function at the moment — but I'm optimistic that'll be done soon.

**Comment by macdonaldster** [comment]
I have been unable to do anything extra for a while but "am back". :) Do you need me to do QA on this or anything else? I can attempt a bug fix if there is something you would like me to check out (I am going through issues now).

**Comment by F4uzan** [comment]
I haven't had much time here myself, but this one in particular did have me in circles. I might need to refactor some of the app-fetching code, since there's a lot of issues with it in both right now and in past versions.

I'll appreciate any PR regarding any of the issues though, as per usual.
